# Generated by Django 5.2 on 2025-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image',
            field=models.ImageField(default=1, upload_to='media/news_image'),
            preserve_default=False,
        ),
    ]
